# -*- coding: utf-8 -*-
"""diptera_inference (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16adS9eMSZ_QwXZ9u0flwn0QTlu8xI_DS

diptera_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_j2xN3MzMMBi4gY34mMwj6tGggC_6akB

# Diptera Larvae Identification — Inference Tool

This notebook loads the pre-trained models and provides a simple web interface
for identifying mosquito larvae from microscopic images.

Requirements:
- The trained models must exist in `MyDrive/diptera_models/`
- Images should be named with the structure type: `larva1-cab.jpg`, `larva1-sif.jpg`, etc.

---
Run all cells. A public link will appear at the end — share it with anyone who needs to use the tool.

**KNOWN LIMITATION:** the public link created by `share=True` only stays alive while
this Colab runtime is connected and running. Once the runtime disconnects (Colab idle
timeout, closing the tab, hitting the ~12h session limit, etc.) the link stops working,
even though the trained `.keras` models remain safely stored in Drive — nothing is lost,
you just need to re-run this notebook (Steps 1-5) to get a new working link. This is a
limitation of using Colab + Gradio's temporary tunnel for a demo, not of the models
themselves; it has been kept as-is (rather than moved to an external host) to keep the
whole project inside Colab/Drive.

## Step 1 - Connect to Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')
print('Drive connected.')

"""## Step 2 - Install Gradio"""

!pip install gradio -q
print('Gradio installed.')

"""## Step 3 - Load models"""

import os
import json
import numpy as np
import tensorflow as tf
from tensorflow import keras
from collections import defaultdict
from pathlib import Path

MODELS_DIR = '/content/drive/MyDrive/diptera_models'
IMG_SIZE   = 224

# Load class names mapping saved during training
with open(f'{MODELS_DIR}/classes.json') as f:
    meta = json.load(f)

genus_class_names  = meta['genus']    # {structure: [class names]}
species_class_names = meta['species'] # {structure: {genus: [class names]}}


def build_embedding_model(model):
    """Same construction used during training: the feature vector produced
    by the CNN right before the final Dropout/Dense(softmax) layers."""
    return keras.Model(inputs=model.input, outputs=model.layers[-3].output)


def load_ood_stats(path):
    """Loads the per-class centroids/thresholds saved during training
    (diptera_estruturas_v3_3.ipynb, Passo 6/7). Returns None if missing
    (e.g. models trained before this feature existed)."""
    if not os.path.exists(path):
        return None
    data = np.load(path)
    return data['centroids'], data['thresholds'], data['valid']


# Load genus models (one per structure)
models_genus = {}
for struct, class_names in genus_class_names.items():
    path = f'{MODELS_DIR}/genus_{struct}.keras'
    if os.path.exists(path):
        model = keras.models.load_model(path)
        emb_model = build_embedding_model(model)
        ood = load_ood_stats(f'{MODELS_DIR}/genus_{struct}_ood.npz')
        models_genus[struct] = (model, class_names, emb_model, ood)
        print(f'Loaded: genus_{struct}.keras  classes={class_names}'
              f'{"  (no OOD stats found)" if ood is None else ""}')

# Load species models (one per structure x genus)
models_species = defaultdict(dict)
for struct, genera in species_class_names.items():
    for genus, class_names in genera.items():
        path = f'{MODELS_DIR}/species_{struct}_{genus}.keras'
        if os.path.exists(path):
            model = keras.models.load_model(path)
            emb_model = build_embedding_model(model)
            ood = load_ood_stats(f'{MODELS_DIR}/species_{struct}_{genus}_ood.npz')
            models_species[struct][genus] = (model, class_names, emb_model, ood)
            print(f'Loaded: species_{struct}_{genus}.keras  classes={class_names}'
                  f'{"  (no OOD stats found)" if ood is None else ""}')

print('\nAll models loaded.')

"""## Step 4 - Define prediction function"""

from PIL import Image


def predict_from_pil(pil_image, model):
    """Run inference on a PIL image and return probability array."""
    img = pil_image.resize((IMG_SIZE, IMG_SIZE)).convert('RGB')
    arr = tf.expand_dims(keras.utils.img_to_array(img), 0)
    return model.predict(arr, verbose=0)[0], arr


def ood_score(embedding, ood):
    """
    Returns an "unknown %" (0-100) for a single structure image, based on
    the distance from its embedding to the nearest known class centroid,
    normalised by that class's reference distance (the max distance seen
    among its own training examples, times a safety margin — see
    compute_ood_stats in the training notebook):

        score = 100 * d / (d + threshold)

    This is NOT "100% - softmax confidence": softmax always splits 100%
    across the known classes, even for an image that does not resemble
    anything the model was trained on. By construction of the threshold,
    any larva similar to the training set gets a low score (comfortably
    below 50%), while a larva far from every centroid (e.g. a species
    absent from the whole dataset) approaches 100%. Returns None if OOD
    stats are unavailable for this model.
    """
    if ood is None:
        return None
    centroids, thresholds, valid = ood
    valid_idx = np.where(valid)[0]
    dists = np.linalg.norm(centroids[valid_idx] - embedding, axis=1)
    i = np.argmin(dists)
    d, thr = dists[i], thresholds[valid_idx[i]]
    if thr <= 0:
        return 0.0 if d == 0 else 100.0
    return float(100 * d / (d + thr))


def format_vote_block(pct_dict, unknown_pct, bar_width=25):
    """
    Formats the combined vote as lines of "name  XX.X%  bars", where the
    known-class percentages (already rescaled to sum to 100 - unknown_pct)
    and the unknown percentage together add up to 100%.
    """
    lines = []
    for name, pct in sorted(pct_dict.items(), key=lambda x: -x[1]):
        bar = '|' * int(round(pct / 100 * bar_width))
        lines.append(f'  {name:<16} {pct:5.1f}%  {bar}')
    bar = '|' * int(round(unknown_pct / 100 * bar_width))
    lines.append(f'  {"Unknown":<16} {unknown_pct:5.1f}%  {bar}')
    return '\n'.join(lines)


def identify_larva(cab_img, seg8_img, segan_img, sif_img):
    """
    Main identification function called by Gradio.
    Accepts up to 4 images (one per structure), any can be None.
    The combined vote is shown as percentages per class plus a single
    "Unknown" slice, all summing to 100% (see ood_score for how the
    unknown share is computed).
    """
    uploaded = {
        'cab':   cab_img,
        'seg8':  seg8_img,
        'segAn': segan_img,
        'sif':   sif_img,
    }
    available = {s: img for s, img in uploaded.items() if img is not None}

    if not available:
        return 'Please upload at least one image.', ''

    # --- Level 1: Genus prediction by weighted voting ---
    genus_votes = defaultdict(float)
    genus_detail_lines = []
    genus_ood_scores = []

    for struct, img in available.items():
        if struct not in models_genus:
            continue
        model, class_names, emb_model, ood = models_genus[struct]
        probs, arr = predict_from_pil(img, model)
        emb = emb_model.predict(arr, verbose=0)[0]
        score = ood_score(emb, ood)
        if score is not None:
            genus_ood_scores.append(score)
        for i, p in enumerate(probs):
            genus_votes[class_names[i]] += float(p)
        genus_detail_lines.append('  ' + struct + ': ' + ', '.join(
            f'{class_names[i]} {probs[i]*100:.1f}%' for i in range(len(class_names))))

    if not genus_votes:
        return 'No genus models available for the uploaded structures.', ''

    total_v       = sum(genus_votes.values())
    genus_unknown = float(np.mean(genus_ood_scores)) if genus_ood_scores else 0.0
    known_share   = 100 - genus_unknown
    genus_pct     = {g: (v / total_v) * known_share for g, v in genus_votes.items()}
    predicted_genus = max(genus_pct, key=genus_pct.get)

    genus_result = 'LEVEL 1 — GENUS\n'
    genus_result += '\n'.join(genus_detail_lines) + '\n\n'
    genus_result += 'Combined vote:\n'
    genus_result += format_vote_block(genus_pct, genus_unknown)
    genus_result += f'\n\n  Most likely genus: {predicted_genus} ({genus_pct[predicted_genus]:.1f}%)'

    # --- Level 2: Species prediction by weighted voting (always computed) ---
    species_votes = defaultdict(float)
    species_detail_lines = []
    species_ood_scores = []

    for struct, img in available.items():
        if struct not in models_species or predicted_genus not in models_species[struct]:
            continue
        model, sp_names, emb_model, ood = models_species[struct][predicted_genus]
        probs, arr = predict_from_pil(img, model)
        emb = emb_model.predict(arr, verbose=0)[0]
        score = ood_score(emb, ood)
        if score is not None:
            species_ood_scores.append(score)
        species_detail_lines.append('  ' + struct + ': ' + ', '.join(
            f'{sp_names[i]} {probs[i]*100:.1f}%' for i in range(len(sp_names))))
        for i, p in enumerate(probs):
            species_votes[sp_names[i]] += float(p)

    if not species_votes:
        species_result = f'No species model available for {predicted_genus}.'
        final = f'\n\nFINAL IDENTIFICATION: {predicted_genus} ({genus_pct[predicted_genus]:.1f}%)'
    else:
        total_sv         = sum(species_votes.values())
        species_unknown  = float(np.mean(species_ood_scores)) if species_ood_scores else 0.0
        sp_known_share   = 100 - species_unknown
        species_pct      = {s: (v / total_sv) * sp_known_share for s, v in species_votes.items()}
        predicted_species = max(species_pct, key=species_pct.get)

        species_result  = f'LEVEL 2 — SPECIES (within {predicted_genus})\n'
        species_result += '\n'.join(species_detail_lines) + '\n\n'
        species_result += 'Combined vote:\n'
        species_result += format_vote_block(species_pct, species_unknown)
        species_result += f'\n\n  Most likely species: {predicted_species} ({species_pct[predicted_species]:.1f}%)'

        final = (
            f'\n\nFINAL IDENTIFICATION: {predicted_genus} {predicted_species}\n'
            f'  Genus:   {genus_pct[predicted_genus]:.1f}%\n'
            f'  Species: {species_pct[predicted_species]:.1f}%'
        )

    return genus_result, species_result + final


print('Prediction function defined.')

"""## Step 5 - Launch Gradio interface"""

import gradio as gr

# Build the interface
with gr.Blocks(title='Diptera Larvae Identification') as app:

    gr.Markdown("""
    # Diptera Larvae Identification
    **IHMT / IPS Bioinformatics Internship**

    Upload microscopic images of a mosquito larva.
    You can upload one or more structures — the more you provide, the more confident the result.

    **Image naming:** files should contain the structure name (cab, seg8, segan, sif).
    Do not upload scale-bar versions (-sc).

    The result shows a percentage for each candidate genus/species, plus a single
    **"Unknown"** slice — all summing to 100%. The Unknown share reflects how far
    the image is from anything seen during training (not just softmax confidence):
    a larva similar to the training set should show a small Unknown share, while
    one from a species outside the whole dataset should show a large one.
    """)

    with gr.Row():
        cab_input   = gr.Image(type='pil', label='Cephalic capsule (cab)')
        seg8_input  = gr.Image(type='pil', label='Segment 8 (seg8)')
        segan_input = gr.Image(type='pil', label='Anal segment (segAn)')
        sif_input   = gr.Image(type='pil', label='Siphon (sif) — not present in Anopheles')

    run_btn = gr.Button('Identify', variant='primary')

    with gr.Row():
        genus_out   = gr.Textbox(label='Level 1 — Genus', lines=12)
        species_out = gr.Textbox(label='Level 2 — Species', lines=12)

    run_btn.click(
        fn=identify_larva,
        inputs=[cab_input, seg8_input, segan_input, sif_input],
        outputs=[genus_out, species_out]
    )

# share=True creates a public link valid for 72 hours
app.launch(share=True)